@baseUrl = http://localhost:3333
@authToken = {{login.response.body.accessToken}}

# @name list_users
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "mail@mail.com",
  "password": "123456"
}

###

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "mail@mail.com",
  "password": "123456"
}