services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: