services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres-auth
    volumes:
      - ./:/usr/src/app
    networks:
      - app-connect

  postgres-auth:
    container_name: postgres-auth
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-connect

volumes:
  data:

networks:
  app-connect:
      driver: bridge